// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FSCMessage.proto

package com.comsince.github.proto;

public final class FSCMessage {
  private FSCMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AddFriendRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string targetUid = 1;
    /**
     * <code>required string targetUid = 1;</code>
     */
    boolean hasTargetUid();
    /**
     * <code>required string targetUid = 1;</code>
     */
    java.lang.String getTargetUid();
    /**
     * <code>required string targetUid = 1;</code>
     */
    com.google.protobuf.ByteString
        getTargetUidBytes();

    // required string reason = 2;
    /**
     * <code>required string reason = 2;</code>
     */
    boolean hasReason();
    /**
     * <code>required string reason = 2;</code>
     */
    java.lang.String getReason();
    /**
     * <code>required string reason = 2;</code>
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * Protobuf type {@code im.AddFriendRequest}
   */
  public static final class AddFriendRequest extends
      com.google.protobuf.GeneratedMessage
      implements AddFriendRequestOrBuilder {
    // Use AddFriendRequest.newBuilder() to construct.
    private AddFriendRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddFriendRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddFriendRequest defaultInstance;
    public static AddFriendRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AddFriendRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddFriendRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              targetUid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              reason_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.comsince.github.proto.FSCMessage.internal_static_im_AddFriendRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.comsince.github.proto.FSCMessage.internal_static_im_AddFriendRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.comsince.github.proto.FSCMessage.AddFriendRequest.class, com.comsince.github.proto.FSCMessage.AddFriendRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AddFriendRequest> PARSER =
        new com.google.protobuf.AbstractParser<AddFriendRequest>() {
      public AddFriendRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddFriendRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddFriendRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string targetUid = 1;
    public static final int TARGETUID_FIELD_NUMBER = 1;
    private java.lang.Object targetUid_;
    /**
     * <code>required string targetUid = 1;</code>
     */
    public boolean hasTargetUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string targetUid = 1;</code>
     */
    public java.lang.String getTargetUid() {
      java.lang.Object ref = targetUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetUid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string targetUid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTargetUidBytes() {
      java.lang.Object ref = targetUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string reason = 2;
    public static final int REASON_FIELD_NUMBER = 2;
    private java.lang.Object reason_;
    /**
     * <code>required string reason = 2;</code>
     */
    public boolean hasReason() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string reason = 2;</code>
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reason_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string reason = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      targetUid_ = "";
      reason_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTargetUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReason()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTargetUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getReasonBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTargetUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getReasonBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.comsince.github.proto.FSCMessage.AddFriendRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.comsince.github.proto.FSCMessage.AddFriendRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.AddFriendRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.comsince.github.proto.FSCMessage.AddFriendRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.AddFriendRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.comsince.github.proto.FSCMessage.AddFriendRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.AddFriendRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.comsince.github.proto.FSCMessage.AddFriendRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.AddFriendRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.comsince.github.proto.FSCMessage.AddFriendRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.comsince.github.proto.FSCMessage.AddFriendRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code im.AddFriendRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.comsince.github.proto.FSCMessage.AddFriendRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.comsince.github.proto.FSCMessage.internal_static_im_AddFriendRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.comsince.github.proto.FSCMessage.internal_static_im_AddFriendRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.comsince.github.proto.FSCMessage.AddFriendRequest.class, com.comsince.github.proto.FSCMessage.AddFriendRequest.Builder.class);
      }

      // Construct using com.comsince.github.proto.FSCMessage.AddFriendRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        targetUid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        reason_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.comsince.github.proto.FSCMessage.internal_static_im_AddFriendRequest_descriptor;
      }

      public com.comsince.github.proto.FSCMessage.AddFriendRequest getDefaultInstanceForType() {
        return com.comsince.github.proto.FSCMessage.AddFriendRequest.getDefaultInstance();
      }

      public com.comsince.github.proto.FSCMessage.AddFriendRequest build() {
        com.comsince.github.proto.FSCMessage.AddFriendRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.comsince.github.proto.FSCMessage.AddFriendRequest buildPartial() {
        com.comsince.github.proto.FSCMessage.AddFriendRequest result = new com.comsince.github.proto.FSCMessage.AddFriendRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.targetUid_ = targetUid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reason_ = reason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.comsince.github.proto.FSCMessage.AddFriendRequest) {
          return mergeFrom((com.comsince.github.proto.FSCMessage.AddFriendRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.comsince.github.proto.FSCMessage.AddFriendRequest other) {
        if (other == com.comsince.github.proto.FSCMessage.AddFriendRequest.getDefaultInstance()) return this;
        if (other.hasTargetUid()) {
          bitField0_ |= 0x00000001;
          targetUid_ = other.targetUid_;
          onChanged();
        }
        if (other.hasReason()) {
          bitField0_ |= 0x00000002;
          reason_ = other.reason_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTargetUid()) {
          
          return false;
        }
        if (!hasReason()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.comsince.github.proto.FSCMessage.AddFriendRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.comsince.github.proto.FSCMessage.AddFriendRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string targetUid = 1;
      private java.lang.Object targetUid_ = "";
      /**
       * <code>required string targetUid = 1;</code>
       */
      public boolean hasTargetUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string targetUid = 1;</code>
       */
      public java.lang.String getTargetUid() {
        java.lang.Object ref = targetUid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          targetUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string targetUid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTargetUidBytes() {
        java.lang.Object ref = targetUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string targetUid = 1;</code>
       */
      public Builder setTargetUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        targetUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string targetUid = 1;</code>
       */
      public Builder clearTargetUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetUid_ = getDefaultInstance().getTargetUid();
        onChanged();
        return this;
      }
      /**
       * <code>required string targetUid = 1;</code>
       */
      public Builder setTargetUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        targetUid_ = value;
        onChanged();
        return this;
      }

      // required string reason = 2;
      private java.lang.Object reason_ = "";
      /**
       * <code>required string reason = 2;</code>
       */
      public boolean hasReason() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string reason = 2;</code>
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string reason = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string reason = 2;</code>
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string reason = 2;</code>
       */
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      /**
       * <code>required string reason = 2;</code>
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reason_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:im.AddFriendRequest)
    }

    static {
      defaultInstance = new AddFriendRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:im.AddFriendRequest)
  }

  public interface AddGroupMemberRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string groupId = 1;
    /**
     * <code>required string groupId = 1;</code>
     */
    boolean hasGroupId();
    /**
     * <code>required string groupId = 1;</code>
     */
    java.lang.String getGroupId();
    /**
     * <code>required string groupId = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    // repeated .im.GroupMember added_member = 2;
    /**
     * <code>repeated .im.GroupMember added_member = 2;</code>
     */
    java.util.List<com.comsince.github.proto.FSCMessage.GroupMember> 
        getAddedMemberList();
    /**
     * <code>repeated .im.GroupMember added_member = 2;</code>
     */
    com.comsince.github.proto.FSCMessage.GroupMember getAddedMember(int index);
    /**
     * <code>repeated .im.GroupMember added_member = 2;</code>
     */
    int getAddedMemberCount();
    /**
     * <code>repeated .im.GroupMember added_member = 2;</code>
     */
    java.util.List<? extends com.comsince.github.proto.FSCMessage.GroupMemberOrBuilder> 
        getAddedMemberOrBuilderList();
    /**
     * <code>repeated .im.GroupMember added_member = 2;</code>
     */
    com.comsince.github.proto.FSCMessage.GroupMemberOrBuilder getAddedMemberOrBuilder(
        int index);

    // repeated int32 to_line = 3;
    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    java.util.List<java.lang.Integer> getToLineList();
    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    int getToLineCount();
    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    int getToLine(int index);
  }
  /**
   * Protobuf type {@code im.AddGroupMemberRequest}
   */
  public static final class AddGroupMemberRequest extends
      com.google.protobuf.GeneratedMessage
      implements AddGroupMemberRequestOrBuilder {
    // Use AddGroupMemberRequest.newBuilder() to construct.
    private AddGroupMemberRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddGroupMemberRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddGroupMemberRequest defaultInstance;
    public static AddGroupMemberRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AddGroupMemberRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddGroupMemberRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              groupId_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                addedMember_ = new java.util.ArrayList<com.comsince.github.proto.FSCMessage.GroupMember>();
                mutable_bitField0_ |= 0x00000002;
              }
              addedMember_.add(input.readMessage(com.comsince.github.proto.FSCMessage.GroupMember.PARSER, extensionRegistry));
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                toLine_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              toLine_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                toLine_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                toLine_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          addedMember_ = java.util.Collections.unmodifiableList(addedMember_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          toLine_ = java.util.Collections.unmodifiableList(toLine_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.comsince.github.proto.FSCMessage.internal_static_im_AddGroupMemberRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.comsince.github.proto.FSCMessage.internal_static_im_AddGroupMemberRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.comsince.github.proto.FSCMessage.AddGroupMemberRequest.class, com.comsince.github.proto.FSCMessage.AddGroupMemberRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AddGroupMemberRequest> PARSER =
        new com.google.protobuf.AbstractParser<AddGroupMemberRequest>() {
      public AddGroupMemberRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddGroupMemberRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddGroupMemberRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string groupId = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private java.lang.Object groupId_;
    /**
     * <code>required string groupId = 1;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string groupId = 1;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          groupId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string groupId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .im.GroupMember added_member = 2;
    public static final int ADDED_MEMBER_FIELD_NUMBER = 2;
    private java.util.List<com.comsince.github.proto.FSCMessage.GroupMember> addedMember_;
    /**
     * <code>repeated .im.GroupMember added_member = 2;</code>
     */
    public java.util.List<com.comsince.github.proto.FSCMessage.GroupMember> getAddedMemberList() {
      return addedMember_;
    }
    /**
     * <code>repeated .im.GroupMember added_member = 2;</code>
     */
    public java.util.List<? extends com.comsince.github.proto.FSCMessage.GroupMemberOrBuilder> 
        getAddedMemberOrBuilderList() {
      return addedMember_;
    }
    /**
     * <code>repeated .im.GroupMember added_member = 2;</code>
     */
    public int getAddedMemberCount() {
      return addedMember_.size();
    }
    /**
     * <code>repeated .im.GroupMember added_member = 2;</code>
     */
    public com.comsince.github.proto.FSCMessage.GroupMember getAddedMember(int index) {
      return addedMember_.get(index);
    }
    /**
     * <code>repeated .im.GroupMember added_member = 2;</code>
     */
    public com.comsince.github.proto.FSCMessage.GroupMemberOrBuilder getAddedMemberOrBuilder(
        int index) {
      return addedMember_.get(index);
    }

    // repeated int32 to_line = 3;
    public static final int TO_LINE_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> toLine_;
    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getToLineList() {
      return toLine_;
    }
    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    public int getToLineCount() {
      return toLine_.size();
    }
    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    public int getToLine(int index) {
      return toLine_.get(index);
    }

    private void initFields() {
      groupId_ = "";
      addedMember_ = java.util.Collections.emptyList();
      toLine_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGroupId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAddedMemberCount(); i++) {
        if (!getAddedMember(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGroupIdBytes());
      }
      for (int i = 0; i < addedMember_.size(); i++) {
        output.writeMessage(2, addedMember_.get(i));
      }
      for (int i = 0; i < toLine_.size(); i++) {
        output.writeInt32(3, toLine_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGroupIdBytes());
      }
      for (int i = 0; i < addedMember_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, addedMember_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < toLine_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(toLine_.get(i));
        }
        size += dataSize;
        size += 1 * getToLineList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.comsince.github.proto.FSCMessage.AddGroupMemberRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.comsince.github.proto.FSCMessage.AddGroupMemberRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.AddGroupMemberRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.comsince.github.proto.FSCMessage.AddGroupMemberRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.AddGroupMemberRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.comsince.github.proto.FSCMessage.AddGroupMemberRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.AddGroupMemberRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.comsince.github.proto.FSCMessage.AddGroupMemberRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.AddGroupMemberRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.comsince.github.proto.FSCMessage.AddGroupMemberRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.comsince.github.proto.FSCMessage.AddGroupMemberRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code im.AddGroupMemberRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.comsince.github.proto.FSCMessage.AddGroupMemberRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.comsince.github.proto.FSCMessage.internal_static_im_AddGroupMemberRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.comsince.github.proto.FSCMessage.internal_static_im_AddGroupMemberRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.comsince.github.proto.FSCMessage.AddGroupMemberRequest.class, com.comsince.github.proto.FSCMessage.AddGroupMemberRequest.Builder.class);
      }

      // Construct using com.comsince.github.proto.FSCMessage.AddGroupMemberRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAddedMemberFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        groupId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (addedMemberBuilder_ == null) {
          addedMember_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          addedMemberBuilder_.clear();
        }
        toLine_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.comsince.github.proto.FSCMessage.internal_static_im_AddGroupMemberRequest_descriptor;
      }

      public com.comsince.github.proto.FSCMessage.AddGroupMemberRequest getDefaultInstanceForType() {
        return com.comsince.github.proto.FSCMessage.AddGroupMemberRequest.getDefaultInstance();
      }

      public com.comsince.github.proto.FSCMessage.AddGroupMemberRequest build() {
        com.comsince.github.proto.FSCMessage.AddGroupMemberRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.comsince.github.proto.FSCMessage.AddGroupMemberRequest buildPartial() {
        com.comsince.github.proto.FSCMessage.AddGroupMemberRequest result = new com.comsince.github.proto.FSCMessage.AddGroupMemberRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupId_ = groupId_;
        if (addedMemberBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            addedMember_ = java.util.Collections.unmodifiableList(addedMember_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.addedMember_ = addedMember_;
        } else {
          result.addedMember_ = addedMemberBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          toLine_ = java.util.Collections.unmodifiableList(toLine_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.toLine_ = toLine_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.comsince.github.proto.FSCMessage.AddGroupMemberRequest) {
          return mergeFrom((com.comsince.github.proto.FSCMessage.AddGroupMemberRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.comsince.github.proto.FSCMessage.AddGroupMemberRequest other) {
        if (other == com.comsince.github.proto.FSCMessage.AddGroupMemberRequest.getDefaultInstance()) return this;
        if (other.hasGroupId()) {
          bitField0_ |= 0x00000001;
          groupId_ = other.groupId_;
          onChanged();
        }
        if (addedMemberBuilder_ == null) {
          if (!other.addedMember_.isEmpty()) {
            if (addedMember_.isEmpty()) {
              addedMember_ = other.addedMember_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAddedMemberIsMutable();
              addedMember_.addAll(other.addedMember_);
            }
            onChanged();
          }
        } else {
          if (!other.addedMember_.isEmpty()) {
            if (addedMemberBuilder_.isEmpty()) {
              addedMemberBuilder_.dispose();
              addedMemberBuilder_ = null;
              addedMember_ = other.addedMember_;
              bitField0_ = (bitField0_ & ~0x00000002);
              addedMemberBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAddedMemberFieldBuilder() : null;
            } else {
              addedMemberBuilder_.addAllMessages(other.addedMember_);
            }
          }
        }
        if (!other.toLine_.isEmpty()) {
          if (toLine_.isEmpty()) {
            toLine_ = other.toLine_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureToLineIsMutable();
            toLine_.addAll(other.toLine_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGroupId()) {
          
          return false;
        }
        for (int i = 0; i < getAddedMemberCount(); i++) {
          if (!getAddedMember(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.comsince.github.proto.FSCMessage.AddGroupMemberRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.comsince.github.proto.FSCMessage.AddGroupMemberRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string groupId = 1;
      private java.lang.Object groupId_ = "";
      /**
       * <code>required string groupId = 1;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupId_ = value;
        onChanged();
        return this;
      }

      // repeated .im.GroupMember added_member = 2;
      private java.util.List<com.comsince.github.proto.FSCMessage.GroupMember> addedMember_ =
        java.util.Collections.emptyList();
      private void ensureAddedMemberIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          addedMember_ = new java.util.ArrayList<com.comsince.github.proto.FSCMessage.GroupMember>(addedMember_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.comsince.github.proto.FSCMessage.GroupMember, com.comsince.github.proto.FSCMessage.GroupMember.Builder, com.comsince.github.proto.FSCMessage.GroupMemberOrBuilder> addedMemberBuilder_;

      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public java.util.List<com.comsince.github.proto.FSCMessage.GroupMember> getAddedMemberList() {
        if (addedMemberBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addedMember_);
        } else {
          return addedMemberBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public int getAddedMemberCount() {
        if (addedMemberBuilder_ == null) {
          return addedMember_.size();
        } else {
          return addedMemberBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public com.comsince.github.proto.FSCMessage.GroupMember getAddedMember(int index) {
        if (addedMemberBuilder_ == null) {
          return addedMember_.get(index);
        } else {
          return addedMemberBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public Builder setAddedMember(
          int index, com.comsince.github.proto.FSCMessage.GroupMember value) {
        if (addedMemberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddedMemberIsMutable();
          addedMember_.set(index, value);
          onChanged();
        } else {
          addedMemberBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public Builder setAddedMember(
          int index, com.comsince.github.proto.FSCMessage.GroupMember.Builder builderForValue) {
        if (addedMemberBuilder_ == null) {
          ensureAddedMemberIsMutable();
          addedMember_.set(index, builderForValue.build());
          onChanged();
        } else {
          addedMemberBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public Builder addAddedMember(com.comsince.github.proto.FSCMessage.GroupMember value) {
        if (addedMemberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddedMemberIsMutable();
          addedMember_.add(value);
          onChanged();
        } else {
          addedMemberBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public Builder addAddedMember(
          int index, com.comsince.github.proto.FSCMessage.GroupMember value) {
        if (addedMemberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddedMemberIsMutable();
          addedMember_.add(index, value);
          onChanged();
        } else {
          addedMemberBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public Builder addAddedMember(
          com.comsince.github.proto.FSCMessage.GroupMember.Builder builderForValue) {
        if (addedMemberBuilder_ == null) {
          ensureAddedMemberIsMutable();
          addedMember_.add(builderForValue.build());
          onChanged();
        } else {
          addedMemberBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public Builder addAddedMember(
          int index, com.comsince.github.proto.FSCMessage.GroupMember.Builder builderForValue) {
        if (addedMemberBuilder_ == null) {
          ensureAddedMemberIsMutable();
          addedMember_.add(index, builderForValue.build());
          onChanged();
        } else {
          addedMemberBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public Builder addAllAddedMember(
          java.lang.Iterable<? extends com.comsince.github.proto.FSCMessage.GroupMember> values) {
        if (addedMemberBuilder_ == null) {
          ensureAddedMemberIsMutable();
          super.addAll(values, addedMember_);
          onChanged();
        } else {
          addedMemberBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public Builder clearAddedMember() {
        if (addedMemberBuilder_ == null) {
          addedMember_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          addedMemberBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public Builder removeAddedMember(int index) {
        if (addedMemberBuilder_ == null) {
          ensureAddedMemberIsMutable();
          addedMember_.remove(index);
          onChanged();
        } else {
          addedMemberBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public com.comsince.github.proto.FSCMessage.GroupMember.Builder getAddedMemberBuilder(
          int index) {
        return getAddedMemberFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public com.comsince.github.proto.FSCMessage.GroupMemberOrBuilder getAddedMemberOrBuilder(
          int index) {
        if (addedMemberBuilder_ == null) {
          return addedMember_.get(index);  } else {
          return addedMemberBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public java.util.List<? extends com.comsince.github.proto.FSCMessage.GroupMemberOrBuilder> 
           getAddedMemberOrBuilderList() {
        if (addedMemberBuilder_ != null) {
          return addedMemberBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addedMember_);
        }
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public com.comsince.github.proto.FSCMessage.GroupMember.Builder addAddedMemberBuilder() {
        return getAddedMemberFieldBuilder().addBuilder(
            com.comsince.github.proto.FSCMessage.GroupMember.getDefaultInstance());
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public com.comsince.github.proto.FSCMessage.GroupMember.Builder addAddedMemberBuilder(
          int index) {
        return getAddedMemberFieldBuilder().addBuilder(
            index, com.comsince.github.proto.FSCMessage.GroupMember.getDefaultInstance());
      }
      /**
       * <code>repeated .im.GroupMember added_member = 2;</code>
       */
      public java.util.List<com.comsince.github.proto.FSCMessage.GroupMember.Builder> 
           getAddedMemberBuilderList() {
        return getAddedMemberFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.comsince.github.proto.FSCMessage.GroupMember, com.comsince.github.proto.FSCMessage.GroupMember.Builder, com.comsince.github.proto.FSCMessage.GroupMemberOrBuilder> 
          getAddedMemberFieldBuilder() {
        if (addedMemberBuilder_ == null) {
          addedMemberBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.comsince.github.proto.FSCMessage.GroupMember, com.comsince.github.proto.FSCMessage.GroupMember.Builder, com.comsince.github.proto.FSCMessage.GroupMemberOrBuilder>(
                  addedMember_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          addedMember_ = null;
        }
        return addedMemberBuilder_;
      }

      // repeated int32 to_line = 3;
      private java.util.List<java.lang.Integer> toLine_ = java.util.Collections.emptyList();
      private void ensureToLineIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          toLine_ = new java.util.ArrayList<java.lang.Integer>(toLine_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getToLineList() {
        return java.util.Collections.unmodifiableList(toLine_);
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public int getToLineCount() {
        return toLine_.size();
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public int getToLine(int index) {
        return toLine_.get(index);
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public Builder setToLine(
          int index, int value) {
        ensureToLineIsMutable();
        toLine_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public Builder addToLine(int value) {
        ensureToLineIsMutable();
        toLine_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public Builder addAllToLine(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureToLineIsMutable();
        super.addAll(values, toLine_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public Builder clearToLine() {
        toLine_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:im.AddGroupMemberRequest)
    }

    static {
      defaultInstance = new AddGroupMemberRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:im.AddGroupMemberRequest)
  }

  public interface GroupMemberOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string memberId = 1;
    /**
     * <code>required string memberId = 1;</code>
     */
    boolean hasMemberId();
    /**
     * <code>required string memberId = 1;</code>
     */
    java.lang.String getMemberId();
    /**
     * <code>required string memberId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMemberIdBytes();

    // optional string alias = 2;
    /**
     * <code>optional string alias = 2;</code>
     */
    boolean hasAlias();
    /**
     * <code>optional string alias = 2;</code>
     */
    java.lang.String getAlias();
    /**
     * <code>optional string alias = 2;</code>
     */
    com.google.protobuf.ByteString
        getAliasBytes();

    // required int32 type = 3;
    /**
     * <code>required int32 type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 3;</code>
     */
    int getType();

    // optional int64 update_dt = 4;
    /**
     * <code>optional int64 update_dt = 4;</code>
     */
    boolean hasUpdateDt();
    /**
     * <code>optional int64 update_dt = 4;</code>
     */
    long getUpdateDt();
  }
  /**
   * Protobuf type {@code im.GroupMember}
   */
  public static final class GroupMember extends
      com.google.protobuf.GeneratedMessage
      implements GroupMemberOrBuilder {
    // Use GroupMember.newBuilder() to construct.
    private GroupMember(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GroupMember(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GroupMember defaultInstance;
    public static GroupMember getDefaultInstance() {
      return defaultInstance;
    }

    public GroupMember getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GroupMember(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              memberId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              alias_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              updateDt_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.comsince.github.proto.FSCMessage.internal_static_im_GroupMember_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.comsince.github.proto.FSCMessage.internal_static_im_GroupMember_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.comsince.github.proto.FSCMessage.GroupMember.class, com.comsince.github.proto.FSCMessage.GroupMember.Builder.class);
    }

    public static com.google.protobuf.Parser<GroupMember> PARSER =
        new com.google.protobuf.AbstractParser<GroupMember>() {
      public GroupMember parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupMember(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GroupMember> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string memberId = 1;
    public static final int MEMBERID_FIELD_NUMBER = 1;
    private java.lang.Object memberId_;
    /**
     * <code>required string memberId = 1;</code>
     */
    public boolean hasMemberId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string memberId = 1;</code>
     */
    public java.lang.String getMemberId() {
      java.lang.Object ref = memberId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          memberId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string memberId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMemberIdBytes() {
      java.lang.Object ref = memberId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memberId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string alias = 2;
    public static final int ALIAS_FIELD_NUMBER = 2;
    private java.lang.Object alias_;
    /**
     * <code>optional string alias = 2;</code>
     */
    public boolean hasAlias() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string alias = 2;</code>
     */
    public java.lang.String getAlias() {
      java.lang.Object ref = alias_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          alias_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string alias = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAliasBytes() {
      java.lang.Object ref = alias_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>required int32 type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    // optional int64 update_dt = 4;
    public static final int UPDATE_DT_FIELD_NUMBER = 4;
    private long updateDt_;
    /**
     * <code>optional int64 update_dt = 4;</code>
     */
    public boolean hasUpdateDt() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 update_dt = 4;</code>
     */
    public long getUpdateDt() {
      return updateDt_;
    }

    private void initFields() {
      memberId_ = "";
      alias_ = "";
      type_ = 0;
      updateDt_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMemberId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMemberIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAliasBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, updateDt_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMemberIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAliasBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, updateDt_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.comsince.github.proto.FSCMessage.GroupMember parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.comsince.github.proto.FSCMessage.GroupMember parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.GroupMember parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.comsince.github.proto.FSCMessage.GroupMember parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.GroupMember parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.comsince.github.proto.FSCMessage.GroupMember parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.GroupMember parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.comsince.github.proto.FSCMessage.GroupMember parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.comsince.github.proto.FSCMessage.GroupMember parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.comsince.github.proto.FSCMessage.GroupMember parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.comsince.github.proto.FSCMessage.GroupMember prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code im.GroupMember}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.comsince.github.proto.FSCMessage.GroupMemberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.comsince.github.proto.FSCMessage.internal_static_im_GroupMember_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.comsince.github.proto.FSCMessage.internal_static_im_GroupMember_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.comsince.github.proto.FSCMessage.GroupMember.class, com.comsince.github.proto.FSCMessage.GroupMember.Builder.class);
      }

      // Construct using com.comsince.github.proto.FSCMessage.GroupMember.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        memberId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        alias_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        updateDt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.comsince.github.proto.FSCMessage.internal_static_im_GroupMember_descriptor;
      }

      public com.comsince.github.proto.FSCMessage.GroupMember getDefaultInstanceForType() {
        return com.comsince.github.proto.FSCMessage.GroupMember.getDefaultInstance();
      }

      public com.comsince.github.proto.FSCMessage.GroupMember build() {
        com.comsince.github.proto.FSCMessage.GroupMember result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.comsince.github.proto.FSCMessage.GroupMember buildPartial() {
        com.comsince.github.proto.FSCMessage.GroupMember result = new com.comsince.github.proto.FSCMessage.GroupMember(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.memberId_ = memberId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.alias_ = alias_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.updateDt_ = updateDt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.comsince.github.proto.FSCMessage.GroupMember) {
          return mergeFrom((com.comsince.github.proto.FSCMessage.GroupMember)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.comsince.github.proto.FSCMessage.GroupMember other) {
        if (other == com.comsince.github.proto.FSCMessage.GroupMember.getDefaultInstance()) return this;
        if (other.hasMemberId()) {
          bitField0_ |= 0x00000001;
          memberId_ = other.memberId_;
          onChanged();
        }
        if (other.hasAlias()) {
          bitField0_ |= 0x00000002;
          alias_ = other.alias_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasUpdateDt()) {
          setUpdateDt(other.getUpdateDt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMemberId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.comsince.github.proto.FSCMessage.GroupMember parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.comsince.github.proto.FSCMessage.GroupMember) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string memberId = 1;
      private java.lang.Object memberId_ = "";
      /**
       * <code>required string memberId = 1;</code>
       */
      public boolean hasMemberId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string memberId = 1;</code>
       */
      public java.lang.String getMemberId() {
        java.lang.Object ref = memberId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          memberId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string memberId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMemberIdBytes() {
        java.lang.Object ref = memberId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memberId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string memberId = 1;</code>
       */
      public Builder setMemberId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        memberId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string memberId = 1;</code>
       */
      public Builder clearMemberId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        memberId_ = getDefaultInstance().getMemberId();
        onChanged();
        return this;
      }
      /**
       * <code>required string memberId = 1;</code>
       */
      public Builder setMemberIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        memberId_ = value;
        onChanged();
        return this;
      }

      // optional string alias = 2;
      private java.lang.Object alias_ = "";
      /**
       * <code>optional string alias = 2;</code>
       */
      public boolean hasAlias() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string alias = 2;</code>
       */
      public java.lang.String getAlias() {
        java.lang.Object ref = alias_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          alias_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string alias = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAliasBytes() {
        java.lang.Object ref = alias_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alias_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string alias = 2;</code>
       */
      public Builder setAlias(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        alias_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string alias = 2;</code>
       */
      public Builder clearAlias() {
        bitField0_ = (bitField0_ & ~0x00000002);
        alias_ = getDefaultInstance().getAlias();
        onChanged();
        return this;
      }
      /**
       * <code>optional string alias = 2;</code>
       */
      public Builder setAliasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        alias_ = value;
        onChanged();
        return this;
      }

      // required int32 type = 3;
      private int type_ ;
      /**
       * <code>required int32 type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 3;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional int64 update_dt = 4;
      private long updateDt_ ;
      /**
       * <code>optional int64 update_dt = 4;</code>
       */
      public boolean hasUpdateDt() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 update_dt = 4;</code>
       */
      public long getUpdateDt() {
        return updateDt_;
      }
      /**
       * <code>optional int64 update_dt = 4;</code>
       */
      public Builder setUpdateDt(long value) {
        bitField0_ |= 0x00000008;
        updateDt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 update_dt = 4;</code>
       */
      public Builder clearUpdateDt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        updateDt_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:im.GroupMember)
    }

    static {
      defaultInstance = new GroupMember(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:im.GroupMember)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_im_AddFriendRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_im_AddFriendRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_im_AddGroupMemberRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_im_AddGroupMemberRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_im_GroupMember_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_im_GroupMember_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020FSCMessage.proto\022\002im\"5\n\020AddFriendReque" +
      "st\022\021\n\ttargetUid\030\001 \002(\t\022\016\n\006reason\030\002 \002(\t\"`\n" +
      "\025AddGroupMemberRequest\022\017\n\007groupId\030\001 \002(\t\022" +
      "%\n\014added_member\030\002 \003(\0132\017.im.GroupMember\022\017" +
      "\n\007to_line\030\003 \003(\005\"O\n\013GroupMember\022\020\n\010member" +
      "Id\030\001 \002(\t\022\r\n\005alias\030\002 \001(\t\022\014\n\004type\030\003 \002(\005\022\021\n" +
      "\tupdate_dt\030\004 \001(\003B\'\n\031com.comsince.github." +
      "protoB\nFSCMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_im_AddFriendRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_im_AddFriendRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_im_AddFriendRequest_descriptor,
              new java.lang.String[] { "TargetUid", "Reason", });
          internal_static_im_AddGroupMemberRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_im_AddGroupMemberRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_im_AddGroupMemberRequest_descriptor,
              new java.lang.String[] { "GroupId", "AddedMember", "ToLine", });
          internal_static_im_GroupMember_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_im_GroupMember_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_im_GroupMember_descriptor,
              new java.lang.String[] { "MemberId", "Alias", "Type", "UpdateDt", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
